### ISSUE TITLE
Add on option to disable rtd-bot in config.yml

### ISSUE THREAD

**Issue by webknjaz** [KengoTODA/readthedocs-action#131]
The motivation is that I'm having GitHub App integration enabled for the whole org.
But I want to prevent bot spamming with config reminders to irrelevant repos. Like a repo with gh-pages hosted static website.

**Comment by KengoTODA** [comment]
v2 doesn't use the `config.yml` so I will close this issue. Instead, we can use [`on`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on) or [`jobs.<job_id>.steps[*].if`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif) in the GitHub Action workflow instead.
